### PR TITLE
Changed system directory to ~/.config/retroarch/system/citra-emu, upd…

### PR DESCRIPTION
**Pull request by TheDarkula**
…ated README.md

### CODE REVIEW

**Comment by twinaphex** [comment]
Umm, sorry, but if I'm understanding correctly how the system directory is being approached for this core, this is dead wrong. A system directory is NEVER at a pre-specified place, and you have to go through the SYSTEM_DIR environment callback in order to grab its path.

**Comment by j-selby** [comment]
@twinaphex no, I am not currently using the SYSTEM_DIR callback - see issue #3. I am waiting for VFS to be implemented on Citra's side. Right now it does default to desktop paths, which is on the roadmap for fixing.

I am not keen to merge this simply because it breaks compatibility with current Citra builds for no tangible benefit, other then changing the hardcoded path, though I will wait for comment from the author before closing.

**Comment by twinaphex** [comment]
Alright, let's hold off until we can finally support the system directory the proper way, this would just constitute a bad hack for now anyways.

**Comment by TheDarkula** [comment]
No worries. I wasn't aware of [#3](https://github.com/libretro/citra/issues/3). I just saw something that didn't match with the usual storage method that retroarch follows and fixed that up.

**Comment by j-selby** [comment]
Correctly implemented in 44960e45800b8a2fa485fa82129974414732a0e1. Thanks for the PR though!

**Comment by TheDarkula** [comment]
Awesome. Just compiled it. Works great!

**Pull request closed without merging**
