### PR TITLE
Update Readme and cleanup Appveyor files

### PR DESCRIPTION
**Pull request by bladeoner**
I updated the Readme based on the new-rebase branch, on the following page you can see an example of what it will look like:
https://github.com/bladeoner/citra/tree/readme

I will also look into the Github CI/CD Workflow soon, when it works the status can be displayed on the front page in the Readme.

### CODE REVIEW

**Comment by bladeoner** [comment]
@m4tsa I hope you are doing fine.

What needs to be done in the new-rebase branch before it can be merged with the master branch?

**Comment by m4tsa** [comment]
> @m4tsa I hope you are doing fine.
> 
> What needs to be done in the new-rebase branch before it can be merged with the master branch?

Testing

**Comment by bladeoner** [comment]
> > @m4tsa I hope you are doing fine.
> > What needs to be done in the new-rebase branch before it can be merged with the master branch?
> 
> Testing

Thank you for your quick response, then I will close this PR as it has no use over the new-rebase branch.

Is the core build from the new-rebase branch somewhere available for testing? If not can you share it?

**Comment by bladeoner** [comment]
@m4tsa Thank you for your quick response, then my PR doesn't have a lot of use.

Is it possible to share the core to test it?

**Comment by bladeoner** [comment]
> > @m4tsa I hope you are doing fine.
> > What needs to be done in the new-rebase branch before it can be merged with the master branch?
> 
> Testing

Thank you for your quick response, then my PR doesn't have a lot of use.

Is it possible to share the core to test it?

**Comment by m4tsa** [comment]
> > > @m4tsa I hope you are doing fine.
> > > What needs to be done in the new-rebase branch before it can be merged with the master branch?
> > 
> > 
> > Testing
> 
> Thank you for your quick response, then my PR doesn't have a lot of use.
> 
> Is it possible to share the core to test it?

I don't have a windows build at hand, but just running make in mingw after cloning the repo with submodules should build.

**Comment by msheehan79** [comment]
@m4tsa thought I would chime in here as I too would love to see this brought up to current and was looking forward to your branch getting merged. 

I was able to build the core for Win x64 based on your comments above, but the first issue I ran into is that whenever I close content or try to exit RetroArch once I start a game, it causes RetroArch to hang and I have to force close the application. 

Saw this with RA 1.9.8 and cleared my RA config and core options so all is defaulted. Is there any required bios or asset files that might be needed, or any specific troubleshooting I should try? Do you want me to log this as an issue here?

image

**Pull request closed without merging**
