### PR TITLE
WIP Update Citra

### LINKED ISSUE #59: Update Citra from upstream
Last update was September 30th, 2018. Would be good to update Citra!

### PR DESCRIPTION
**Pull request by RobLoach**
**DO NOT MERGE THIS!**

@j-selby I've brought the changes in from master, and manged to update a few things. Getting the following error, however...

``` log
citra/src/citra_libretro/citra_libretro.cpp: In function ‘void* retro_get_memory_data(unsigned int)’:
citra/src/citra_libretro/citra_libretro.cpp:526:24: error: ‘memory_regions’ is not a member of ‘Kernel’
         return Kernel::memory_regions[0].linear_heap_memory->data();
                        ^~~~~~~~~~~~~~
```

Do you happen to know where Kernel memory_regions went?

## References
- Fixes #59

### CODE REVIEW

**Comment by j-selby** [comment]
Hi!

Sorry for the late response.

It got moved into https://github.com/citra-emu/citra/blob/fdb5a8c2df1a5e0b4c4494d2499c67a3c6ac85e7/src/core/hle/kernel/kernel.h - you will need to look into mutexes to get access to it now. I would suggest to just remove this, as there is no public usage of this API for Citra, and the LibRetro API doesn't really allow for async returns.

**Comment by RobLoach** [comment]
Thanks! Without the memory data and size usage, it allows it to compile. However, running into a trace trap when it's run...

```
[INFO] [GL]: Creating FBO 0 @ 32768x32768
[INFO] [GL]: Initializing HW render (8192 x 8192).
[INFO] [GL]: Max texture size: 32768 px, renderbuffer size: 32768 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: x11
[INFO] Found shader "/home/rob/.config/retroarch/shaders/retroarch.glslp"
[INFO] Environ SET_GEOMETRY.
[INFO] SET_GEOMETRY: 400x480, aspect: 0.833.
[1]    11630 trace trap (core dumped)  retroarch -L src/citra_libretro/citra_libretro.so
```

**Comment by j-selby** [comment]
Can you get a trace log for that one?

**Comment by celerizer** [comment]
Got a trace with drmingw, looked to be something related to shaders:
https://hastebin.com/raw/alevomeqen
Commenting out the offending assertation:

`ASSERT_MSG(result == GL_TRUE, "Shader not linked")`

At `src\video_core\renderer_opengl\gl_shader_util.cpp` made it compile/run for me.

image

**Comment by j-selby** [comment]
@celerizer commenting out an assertion isn't a solution, and isn't one that I would be willing to merge. It would be great if you could work out *why* that assertion is erroring.

**Comment by RobLoach** [comment]
@j-selby I agree, we should find where the error comes from.

@celerizer pointed out in https://github.com/RobLoach/citra/pull/1#issuecomment-486885952
```
Vertex info
-----------
0(3) : error C0204: version directive must be first statement and may not be repeated
(0) : error C2003: incompatible options for link

Fragment info
-------------
0(3) : error C0204: version directive must be first statement and may not be repeated
(0) : error C2003: incompatible options for link
```

**Comment by celerizer** [comment]
Is this good to be merged now?

**Comment by guoyunhe** [comment]
is this still in progress?

**Comment by RobLoach** [comment]
Negative. Needs some fixes.

**Comment by dankcushions** [comment]
closed during hack-gate 2020. @twinaphex please re-open :)

**Comment by guoyunhe** [comment]
@twinaphex can you reopen it?

**Comment by twinaphex** [comment]
Unfortunately the option to 'Reopen and comment' is greyed out for us.

**Pull request closed without merging**
