### PR TITLE
Add option to disable mouse input for touchscreen

### PR DESCRIPTION
**Pull request by Bezier89**
I have my controller set to use the right joystick to move the mouse. Unfortunately there is currently no way to disable mouse input from affecting the touch screen in the Citra core, and having it receive input from the both the right analog and the "mouse" simultaneously causes pretty erratic results. It is possible to disable the controller from affecting the touch screen (setting right analog function to c-stick) and only use mouse input, but mouse input is currently broken (https://github.com/libretro/citra/issues/23) and fixing that seems more difficult.

It's a fairly simple PR so hopefully it works as expected, but I haven't tested since I'm not sure how to compile the Citra core. Are there instructions anywhere? I followed the instructions [here](https://github.com/citra-emu/citra/wiki/Building-For-Windows#mingw-w64-build-with-msys2) (just replacing the default citra repo with the libretro one) and managed to build citra.exe, but not the *.dll file that is the libretro core.

### CODE REVIEW

**Comment by Bezier89** [comment]
Was able to build the core (just had to set ENABLE_LIBRETRO to ON). I've tested this and after fixing a small bug it now behaves as expected. @j-selby (or anyone else that would be appropriate), this PR is ready for review. Assuming it's approved, should I make a similar PR in the canary branch?

**Comment by Bezier89** [comment]
@j-selby or others, any thoughts on merging this?

**Comment by j-selby** [comment]
@Bezier89 hi!

PR looks fine, though I do want to wait for the rebasing PR to be completed before I merge any more features.

Thanks for the contribution though - I'll get it in ASAP after that is done.

**Comment by twinaphex** [comment]
Hi @j-selby, would like to know what the status of this PR is and if we can merge it or not.

**Comment by Bezier89** [comment]
@twinaphex @j-selby Any thoughts on merging this? Doesn't look like rebase PR is going to happen any time soon, and this should be fairly independent from that anyway.

**Comment by j-selby** [comment]
@Bezier89 yep, totally  fair enough! Merging now.

**Pull request merged**
